# Generated by Django 4.2.1 on 2023-09-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_journal_journalentry_journalcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_no',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
